
//Help
export const FETCH_HELP_ERROR = 'FETCH_HELP_ERROR';
export const FETCH_HELP_LOADING = 'FETCH_HELP_LOADING';
export const FETCH_HELP_SUCCESS = 'FETCH_HELP_SUCCESS';


//Rubrique
export const FETCH_RUBRIQUE_ERROR = 'FETCH_RUBRIQUE_ERROR';
export const FETCH_RUBRIQUE_LOADING = 'FETCH_RUBRIQUE_LOADING';
export const FETCH_RUBRIQUE_SUCCESS = 'FETCH_RUBRIQUE_SUCCESS';

//Product
export const FETCH_PRODUCT_ERROR ='FETCH_PRODUCT_ERROR'
export const FETCH_PRODUCT_LOADING ='FETCH_PRODUCT_LOADING'
export const FETCH_PRODUCT_SUCCESS ='FETCH_PRODUCT_SUCCESS'


//sponsor
export const FETCH_SPONSOR_ERROR='FETCH_SPONSOR_ERROR'
export const FETCH_SPONSOR_LOADING='FETCH_SPONSOR_LOADING'
export const FETCH_SPONSOR_SUCCESS= 'FETCH_SPONSOR_SUCCESS';


//about
export const FETCH_ABOUT_ERROR='FETCH_ABOUT_ERROR'
export const FETCH_ABOUT_LOADING='FETCH_ABOUT_LOADING'
export const FETCH_ABOUT_SUCCESS='FETCH_ABOUT_SUCCESS'


// action
export const FETCH_ACTION_ERROR= 'FETCH_ACTION_ERROR'
export const FETCH_ACTION_LOADING = 'FETCH_ACTION_LOADING'
export const FETCH_ACTION_SUCCESS = 'FETCH_ACTION_SUCCESS'


//contact

export const FETCH_CONTACT_ERROR='FETCH_CONTACT_ERROR'
export const FETCH_CONTACT_LOADING='FETCH_CONTACT_LOADING'
export const FETCH_CONTACT_SUCCESS ='FETCH_CONTACT_SUCCESS'


//Project
export const FETCH_PROJECT_ERROR= 'FETCH_PROJECT_ERROR'
export const FETCH_PROJECT_LOADING = 'FETCH_PROJECT_LOADING'
export const FETCH_PROJECT_SUCCESS ='FETCH_PROJECT_SUCCESS'


//slide

export const FETCH_SLIDE_ERROR='FETCH_SLIDE_ERROR'
export const FETCH_SLIDE_LOADING ='FETCH_SLIDE_LOADING'
export const FETCH_SLIDE_SUCCESS='FETCH_SLIDE_SUCCESS'
