

export const FETCH_SPOT_ERROR = 'FETCH_SPOT_ERROR';
export const FETCH_SPOT_LOADING = 'FETCH_SPOT_LOADING';
export const FETCH_SPOT_SUCCESS = 'FETCH_SPOT_SUCCESS';



// action
export const FETCH_ACTION_ERROR= 'FETCH_ACTION_ERROR'
export const FETCH_ACTION_LOADING = 'FETCH_ACTION_LOADING'
export const FETCH_ACTION_SUCCESS = 'FETCH_ACTION_SUCCESS'


//contact

export const FETCH_CONTACT_ERROR='FETCH_CONTACT_ERROR'
export const FETCH_CONTACT_LOADING='FETCH_CONTACT_LOADING'
export const FETCH_CONTACT_SUCCESS ='FETCH_CONTACT_SUCCESS'

//commetList

export const FETCH_COMMENTLIST_ERROR ="FETCH_COMMENTLIST_ERROR"
export const FETCH_COMMENTLIST_LOADING ="FETCH_COMMENTLIST_LOADING"
export const FETCH_COMMENTLIST_SUCCESS ="FETCH_COMMENTLIST_SUCCESS"