
/*  Members types actions  */
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const ADD_MEMBER_ERROR = 'ADD_MEMBER_ERROR';
export const ADD_MEMBER_LOADING = 'ADD_MEMBER_LOADING';
export const ADD_MEMBER_SUCCESS = 'ADD_MEMBER_SUCCESS';

export const UPDATE_MEMBER_ERROR = 'UPDATE_MEMBER_ERROR';
export const UPDATE_MEMBER_LOADING = 'UPDATE_MEMBER_LOADING';
export const UPDATE_MEMBER_SUCCESS = 'UPDATE_MEMBER_SUCCESS';


export const FETCH_MEMBER_ERROR = 'FETCH_MEMBER_ERROR';
export const FETCH_MEMBER_LOADING = 'FETCH_MEMBER_LOADING';
export const FETCH_MEMBER_SUCCESS = 'FETCH_MEMBER_SUCCESS';


export const FETCH_BY_ID_MEMBER_ERROR = 'FETCH_BY_ID_MEMBER_ERROR';
export const FETCH_BY_ID_MEMBER_LOADING = 'FETCH_BY_ID_MEMBER_LOADING';
export const FETCH_BY_ID_MEMBER_SUCCESS = 'FETCH_BY_ID_MEMBER_SUCCESS';

export const DELETE_MEMBER_ERROR = 'DELETE_MEMBER_ERROR';
export const DELETE_MEMBER_LOADING = 'DELETE_MEMBER_LOADING';
export const DELETE_MEMBER_SUCCESS = 'DELETE_MEMBER_SUCCESS';


/*  Rubriques types actions  */

export const ADD_OBJECTIF_ERROR = 'ADD_OBJECTIF_ERROR';
export const ADD_OBJECTIF_LOADING = 'ADD_OBJECTIF_LOADING';
export const ADD_OBJECTIF_SUCCESS = 'ADD_OBJECTIF_SUCCESS';

export const UPDATE_OBJECTIF_ERROR = 'UPDATE_OBJECTIF_ERROR';
export const UPDATE_OBJECTIF_LOADING = 'UPDATE_OBJECTIF_LOADING';
export const UPDATE_OBJECTIF_SUCCESS = 'UPDATE_OBJECTIF_SUCCESS';


export const FETCH_OBJECTIF_ERROR = 'FETCH_OBJECTIF_ERROR';
export const FETCH_OBJECTIF_LOADING = 'FETCH_OBJECTIF_LOADING';
export const FETCH_OBJECTIF_SUCCESS = 'FETCH_OBJECTIF_SUCCESS';


export const DELETE_OBJECTIF_ERROR = 'DELETE_OBJECTIF_ERROR';
export const DELETE_OBJECTIF_LOADING = 'DELETE_OBJECTIF_LOADING';
export const DELETE_OBJECTIF_SUCCESS = 'DELETE_OBJECTIF_SUCCESS';

export const ADD_PRESENTATION_ERROR = 'ADD_PRESENTATION_ERROR';
export const ADD_PRESENTATION_LOADING = 'ADD_PRESENTATION_LOADING';
export const ADD_PRESENTATION_SUCCESS = 'ADD_PRESENTATION_SUCCESS';

export const UPDATE_PRESENTATION_ERROR = 'UPDATE_PRESENTATION_ERROR';
export const UPDATE_PRESENTATION_LOADING = 'UPDATE_PRESENTATION_LOADING';
export const UPDATE_PRESENTATION_SUCCESS = 'UPDATE_PRESENTATION_SUCCESS';


export const FETCH_PRESENTATION_ERROR = 'FETCH_PRESENTATION_ERROR';
export const FETCH_PRESENTATION_LOADING = 'FETCH_PRESENTATION_LOADING';
export const FETCH_PRESENTATION_SUCCESS = 'FETCH_PRESENTATION_SUCCESS';


export const DELETE_PRESENTATION_ERROR = 'DELETE_PRESENTATION_ERROR';
export const DELETE_PRESENTATION_LOADING = 'DELETE_PRESENTATION_LOADING';
export const DELETE_PRESENTATION_SUCCESS = 'DELETE_PRESENTATION_SUCCESS';

export const ADD_SPONSOR_ERROR = 'ADD_SPONSOR_ERROR';
export const ADD_SPONSOR_LOADING = 'ADD_SPONSOR_LOADING';
export const ADD_SPONSOR_SUCCESS = 'ADD_SPONSOR_SUCCESS';

export const UPDATE_SPONSOR_ERROR = 'UPDATE_SPONSOR_ERROR';
export const UPDATE_SPONSOR_LOADING = 'UPDATE_SPONSOR_LOADING';
export const UPDATE_SPONSOR_SUCCESS = 'UPDATE_SPONSOR_SUCCESS';


export const FETCH_SPONSOR_ERROR = 'FETCH_SPONSOR_ERROR';
export const FETCH_SPONSOR_LOADING = 'FETCH_SPONSOR_LOADING';
export const FETCH_SPONSOR_SUCCESS = 'FETCH_SPONSOR_SUCCESS';


export const DELETE_SPONSOR_ERROR = 'DELETE_SPONSOR_ERROR';
export const DELETE_SPONSOR_LOADING = 'DELETE_SPONSOR_LOADING';
export const DELETE_SPONSOR_SUCCESS = 'DELETE_SPONSOR_SUCCESS';


export const ADD_PROJET_ERROR = 'ADD_PROJET_ERROR';
export const ADD_PROJET_LOADING = 'ADD_PROJET_LOADING';
export const ADD_PROJET_SUCCESS = 'ADD_PROJET_SUCCESS';

export const UPDATE_PROJET_ERROR = 'UPDATE_PROJET_ERROR';
export const UPDATE_PROJET_LOADING = 'UPDATE_PROJET_LOADING';
export const UPDATE_PROJET_SUCCESS = 'UPDATE_PROJET_SUCCESS';


export const FETCH_PROJET_ERROR = 'FETCH_PROJET_ERROR';
export const FETCH_PROJET_LOADING = 'FETCH_PROJET_LOADING';
export const FETCH_PROJET_SUCCESS = 'FETCH_PROJET_SUCCESS';


export const DELETE_PROJET_ERROR = 'DELETE_PROJET_ERROR';
export const DELETE_PROJET_LOADING = 'DELETE_PROJET_LOADING';
export const DELETE_PROJET_SUCCESS = 'DELETE_PROJET_SUCCESS';



export const ADD_HELP_ERROR = 'ADD_HELP_ERROR';
export const ADD_HELP_LOADING = 'ADD_HELP_LOADING';
export const ADD_HELP_SUCCESS = 'ADD_HELP_SUCCESS';

export const UPDATE_HELP_ERROR = 'UPDATE_HELP_ERROR';
export const UPDATE_HELP_LOADING = 'UPDATE_HELP_LOADING';
export const UPDATE_HELP_SUCCESS = 'UPDATE_HELP_SUCCESS';


export const FETCH_HELP_ERROR = 'FETCH_HELP_ERROR';
export const FETCH_HELP_LOADING = 'FETCH_HELP_LOADING';
export const FETCH_HELP_SUCCESS = 'FETCH_HELP_SUCCESS';


export const DELETE_HELP_ERROR = 'DELETE_HELP_ERROR';
export const DELETE_HELP_LOADING = 'DELETE_HELP_LOADING';
export const DELETE_HELP_SUCCESS = 'DELETE_HELP_SUCCESS';



export const ADD_CONTACT_ERROR = 'ADD_CONTACT_ERROR';
export const ADD_CONTACT_LOADING = 'ADD_CONTACT_LOADING';
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS';

export const UPDATE_CONTACT_ERROR = 'UPDATE_CONTACT_ERROR';
export const UPDATE_CONTACT_LOADING = 'UPDATE_CONTACT_LOADING';
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';


export const FETCH_CONTACT_ERROR = 'FETCH_CONTACT_ERROR';
export const FETCH_CONTACT_LOADING = 'FETCH_CONTACT_LOADING';
export const FETCH_CONTACT_SUCCESS = 'FETCH_CONTACT_SUCCESS';


export const DELETE_CONTACT_ERROR = 'DELETE_CONTACT_ERROR';
export const DELETE_CONTACT_LOADING = 'DELETE_CONTACT_LOADING';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';



export const ADD_ACTION_ERROR = 'ADD_ACTION_ERROR';
export const ADD_ACTION_LOADING = 'ADD_ACTION_LOADING';
export const ADD_ACTION_SUCCESS = 'ADD_ACTION_SUCCESS';

export const UPDATE_ACTION_ERROR = 'UPDATE_ACTION_ERROR';
export const UPDATE_ACTION_LOADING = 'UPDATE_ACTION_LOADING';
export const UPDATE_ACTION_SUCCESS = 'UPDATE_ACTION_SUCCESS';


export const FETCH_ACTION_ERROR = 'FETCH_ACTION_ERROR';
export const FETCH_ACTION_LOADING = 'FETCH_ACTION_LOADING';
export const FETCH_ACTION_SUCCESS = 'FETCH_ACTION_SUCCESS';


export const DELETE_ACTION_ERROR = 'DELETE_ACTION_ERROR';
export const DELETE_ACTION_LOADING = 'DELETE_ACTION_LOADING';
export const DELETE_ACTION_SUCCESS = 'DELETE_ACTION_SUCCESS';